name: dreamapp
description: "Second miniproject"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  provider: ^6.0.0
  fl_chart: ^0.69.0
  sqflite: ^2.4.0
  flare_flutter: ^3.0.2
  video_player: ^2.9.2      # For video playback
  flutter_animate: ^2.0.0  
  google_fit: ^0.0.0  # Check for the latest version
  health: ^11.1.0  # Check for the latest version
  sensors_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.2.2

flutter:
  assets:
    - assets/images/splash.gif
    - assets/images/background.png
    - assets/icons/home.png
    - assets/icons/add.png
    - assets/icons/setting.png
    - assets/icons/favorite.png
    - assets/icons/list.png
    - assets/icons/track.png
    - assets/icons/interpret.png
    - assets/icons/back.png
    - assets/icons/timer.png
    - assets/icons/stop.png
    - assets/icons/nightlight.png
    - assets/icons/play.png
